import {
  Atom,
  BadgeDollarSign,
  Binary,
  BookOpen,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  Calculator,
  ChartNoAxesCombined,
  Code2,
  Database,
  Dna,
  Dumbbell,
  Earth,
  FlaskConical,
  Gavel,
  GraduationCap,
  Languages,
  Landmark,
  Leaf,
  Lightbulb,
  Microscope,
  Palette,
  Scale,
  ShieldCheck,
  Stethoscope,
  Wrench,
  Zap,
} from 'lucide-react';

const iconMap = {
  technology: Binary,
  code: Code2,
  web: Earth,
  database: Database,
  ai: BrainCircuit,
  security: ShieldCheck,
  math: Calculator,
  physics: Atom,
  chemistry: FlaskConical,
  biology: Dna,
  economics: ChartNoAxesCombined,
  business: BriefcaseBusiness,
  accounting: BadgeDollarSign,
  finance: Landmark,
  language: Languages,
  law: Scale,
  medicine: Stethoscope,
  electricity: Zap,
  mechanics: Wrench,
  construction: Building2,
  education: GraduationCap,
  softskills: Lightbulb,
  design: Palette,
  sports: Dumbbell,
  science: Microscope,
  legal: Gavel,
  robot: Bot,
  book: BookOpen,
  leaf: Leaf,
};

export default function CategoryIcon({ name = 'leaf', size = 22 }) {
  const Icon = iconMap[name] || Leaf;
  return <Icon size={size} />;
}
